#!/usr/bin/env python3
"""
Generate the makefiles the Tenth Edition never had either.

    v10/mk/mkdep.py            # regenerate v10/mk/gen/*.mk
    v10/mk/mkdep.py --check    # fail if the committed output is stale

V8 needed this because `usr/src/cmd` is 168 loose `.c` files under a directory
with no makefile in it. B2.0 measured V10's tree and found the same shape --
207 loose `.c` files, no makefile at `cmd/`, and no world build anywhere. The
one candidate, `src/makefile`, builds a Datakit daemon called `fshare`.

So this is `v8/mk/mkdep.py`'s sibling, not its copy: the machinery lives in
`mk/mkgen.py` and what is here is what differs between the two editions --
the toolchain, the header set, the install oracle and the exceptions.

WHAT IS DIFFERENT, AND IT IS SHORTER THAN THE SIMILARITY

  no bootstrap    V8's generator opens with a 136-line STAGE1 table building
                  yacc, make, lex, cpp, ccom, c2, as, ld, ar... because a
                  self-hosting build has to make its own compiler first. V10's
                  compiler, assembler and libc are IN THE TARBALL as linked
                  VAX binaries and run on the V8 kernel (B1, 9/9), so there is
                  no stage 1 here at all. `tools/v10-toolchain.sh` assembles
                  the seven passes and `cc -B/usr/v10/lib/ -t02palc` drives
                  them.

  a paper oracle  V8's install paths were MEASURED off the shipped image.
                  V10 has no image -- making one is B3 -- so the paths come
                  from V10's own manual where it states them and from V8's
                  measurements where it does not. tools/v10-where.py, and the
                  two sources agree everywhere both speak.

  r70 headers     `-I` points at V10's own include tree, not V8's. B2.0 built
                  15 of 17 boot-path commands that way against 10 the other
                  way, so this is measured rather than assumed.
"""

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
V10 = os.path.dirname(HERE)                 # <repo>/v10
ROOT = os.path.dirname(V10)
GEN = os.path.join(HERE, "gen")

# The tree itself is NOT in git -- 25,682 files rebuilt from the TUHS tarballs
# by tools/v10-import.py, so the tarballs stay pristine and our changes stay a
# patch series. v10/MANIFEST is the committed record that our copy is
# complete and unaltered.
SRC = os.path.join(ROOT, "work/v10/src")
INC = os.path.join(ROOT, "work/v10/include")

sys.path.insert(0, os.path.join(ROOT, "mk"))
import mkgen                                                  # noqa: E402


PREAMBLE = """\
# Generated by v10/mk/mkdep.py -- do not edit; edit the generator.
#
# Run from the component's object directory:
#     make -f $SRC/../mk/%(name)s.mk DESTDIR=... install
#
# Every object below depends on the compiler passes that produced it, so
# replacing $(CCOM) rebuilds all of them; every binary depends on $(LD) and
# $(LIBC).

# Source is READ ONLY and lives on the netfs share -- the whole 243 MB tree is
# served, never copied, so no subset ever has to be chosen.  Objects are
# written into the current directory, which the driver makes a per-component
# directory on a writable filesystem.
SRC     = /n/v10/src

# TWO destinations, and neither is `/'.
#
# DESTDIR is the V10 system being assembled -- the tree that becomes the
# image.  TOOLDIR is where tools that RUN ON THE HOST are installed, beside
# the V10 toolchain and off V8's PATH.
#
# A DEFAULT IS LOAD-BEARING HERE.  An unset $(TOOLDIR) expands to nothing, so
# `cp v10mkbitfs $(TOOLDIR)/bin/v10mkbitfs' would write into the HOST's /bin.
# That is not hypothetical -- this file shipped without a TOOLDIR line, and
# the only thing between it and V8's /bin was that nothing had run the
# install target yet.
DESTDIR = /b/v10root
TOOLDIR = /usr/v10

# Our corrections, served beside the pristine tree rather than patched into
# it -- v10/MANIFEST is the record that our copy of the tarball is unaltered,
# and that is worth more than the convenience.  A rule below reading $(SRC)
# is Bell Labs'; one reading $(OURS) is ours.  See v10/src/PATCHES.md.
OURS    = /n/v10ours

# THE TOOLCHAIN IS V10's, AND V8 SUPPLIES ONLY THE DRIVER.
#
# -B names the directory holding the passes; -t says which passes to take from
# there.  `-t02palc' is S5's extended form -- 0 ccom, 2 c2, p cpp, a as, l ld,
# c crt0.o+libc.a -- so one prefix seals every program cc executes.  That seal
# was built so V8's own build could not reach into the running system; it
# turns out to be the lever that points a cc at another EDITION.
#
# $(CC) is what a rule runs.  $(CCPATH) is the file whose timestamp means "the
# compiler changed", which is what a prerequisite list needs -- writing
# `CC = cc' and then using $(CC) as a prerequisite gives
#	Make:  Don't know how to make cc.  Stop.
# on every component at once.
V10LIB   = /usr/v10/lib
CC       = cc -B$(V10LIB)/ -t02palc
CCPATH   = /bin/cc
YACC     = yacc
YACCPATH = /usr/bin/yacc
LEX      = lex
LEXPATH  = /usr/bin/lex
CPP  = $(V10LIB)/cpp
CCOM = $(V10LIB)/ccom
C2   = $(V10LIB)/c2
AS   = $(V10LIB)/as
LD   = $(V10LIB)/ld
AR   = /bin/ar
LIBC = $(V10LIB)/libc.a

# V10's own headers, copied to local disk rather than read off the share:
# netfs costs a round trip per path component, and a header is opened once per
# object that includes it.  tools/v10-bootpath.sh stages them with one
# `cpio -pd'.
INCDIR = /usr/v10/include

CFLAGS = -O %(cflags)s
INCS   = %(incs)s -I$(INCDIR)
COMPILE = $(CC) $(CFLAGS) $(INCS) -c
TOOLS  = $(CCPATH) $(CCOM) $(CPP) $(C2) $(AS)

"""

V10ED = mkgen.Edition(name="v10", root=SRC, incdir=INC,
                      here=HERE, gen=GEN, preamble=PREAMBLE)

WHERE = mkgen.load_where(V10ED)


# The seventeen B3 cannot start without.  Held explicitly rather than derived,
# because the ORDER and the membership are the point: this is the list that
# decides whether a disk boots, and a heuristic that quietly dropped one would
# be found at `/etc/init: not found' with the disk already built.
#
# It is also the set with NO prebuilt binary -- not one of the 46 command
# units with a 1995 binary is here, because these get installed rather than
# left where they were compiled.  There is no oracle for this list.
BOOTPATH = ["init", "getty", "login", "mount", "umount", "mkfs", "fsck",
            "icheck", "sync", "date", "stty", "cat", "cp", "mv", "rm",
            "mkdir", "echo"]

# The subset that MAKES a Tenth Edition filesystem, ported to run on the
# Eighth Edition host.  Built from V10 source and nothing else: V8 has files
# of the same names -- mkbitfs.c, mkfs.c -- and they are eight years apart,
# so using V8's would be assuming the on-disk format never changed rather
# than reading V10's own answer to it.
#
# `mkbitfs' is the one that matters.  seki's root is `ra 0100', and
# BITFS(dev) = ((dev) & 64), so its root filesystem is the BITMAPPED variant:
# 4096-byte blocks, and free space held in S_bfree[BITMAP] rather than in the
# S_free[] list.  mkfs writes only the free-list form -- it is a Berkeley 4.2
# file that uses BSIZE(0) throughout -- so mkfs alone cannot make a
# filesystem seki can mount.  mkbitfs can: it opens with
#
#	#define ISBIT 0100    /* this is a bitmapped filesystem -- fake out macros */
#	#define ICOUNT INOPB(ISBIT)
#	#define BCOUNT BSIZE(ISBIT)
#
# and sets s_valid = 1.  It checks BITFS(st_rdev) on its target, so the raw
# device node it is pointed at must carry bit 6 in its minor number.
# NAMED v10<tool>, AND THAT IS A SAFETY PROPERTY, NOT A CONVENTION.
#
# These run on the EIGHTH Edition host, beside V8's own mkfs, mknod, dd and
# cpio.  A V10 tool that answered to `mkfs' on that machine would be one
# PATH accident away from being the one a build reached for, and the failure
# would be silent: V10's mkfs writes a superblock V8's kernel reads
# differently, so the damage would appear later, somewhere else, as a
# corrupt filesystem.
#
# The tape shows how bad this gets left to convention.  V10's own
# cmd/ccom/vax/makefile carries
#
#	install:
#		cp /lib/ccom comp.sv
#		cp comp /lib/ccom
#
# -- it overwrites the compiler you are compiling with, in `/', on the host.
# Nothing generated here can do that (every destination goes through
# $(DESTDIR) or $(TOOLDIR), asserted below), but the names make the
# separation visible rather than merely true.
#
# Files that go INTO the V10 image keep their real names: `init' has to be
# /etc/init there.  The prefix is only for tools executed on the host.
FSTOOL_SRC = ["mkbitfs", "mknod", "dd", "cpio"]
FSTOOLS = ["v10" + n for n in FSTOOL_SRC]

# A machine you can STOP.  Deliberately not folded into BOOTPATH, whose
# comment is about what a boot needs and would stop being true.
#
# The first golden shipped without either and that was a real defect, because
# V10's shutdown is not V8's.  lsys/md/machdep.c, entire:
#
#	boot(howto)  { if (howto&RB_HALT) death(); reboot(1); }
#	death()      { splx(0x1f); printf("death\n"); for (;;) ; }
#
# V8's boot() calls update(), prints `syncing disks... ', and sleeps five
# lbolt ticks for the I/O to drain.  V10 deleted all of it -- RB_NOSYNC is
# defined in lsys/sys/reboot.h and referenced NOWHERE -- so on a Tenth Edition
# machine the userland sync is the only flush there is, and `sleep' is not a
# convenience but the wait that V8 does inside the kernel and V10 does not do
# at all.  sync(2) -> update() -> bflush(NODEV) issues B_ASYNC writes and
# returns (lsys/io/bio.c:692), so without the wait the disk is stopped with
# blocks still in core.
SHUTDOWN = ["halt", "sleep"]

# The tools the BOOTSTRAP ITSELF needs, none of which the first golden has.
#
# Measured, not guessed: the golden carries 57 prebuilt 1995 binaries plus
# what BOOTPATH builds, and `ar', `cmp', `tail', `grep' and `wc' are in
# neither set.  Two of those are not conveniences --
#
#	ar    stage 2 IS an archive.  libc.a cannot be built without it, and
#	      the preamble's `AR = /bin/ar' names a file that does not exist.
#	cmp   stage 3 IS a comparison.  The fixpoint is "stage 1 and stage 3
#	      produced the same bytes", so with no cmp there is no stage 3 --
#	      only an assertion that both runs exited zero, which is the kind
#	      of check this project has already been caught by.
#
#	ed    stage 2 EDITS A COMPILED FILE.  libc's errlst.o is compiled to
#	      assembly, run through gen/:errfix, and only then assembled -- the
#	      tape's own recipe, and :errfix is an ed script.  Without ed the
#	      error table stays in .data instead of shared text, which builds
#	      and runs and is not what Bell Labs shipped.
#
# `tail' is a convenience and is here anyway, because without it a failed
# build in a guest harness can only be shown with `cat' of a whole log, and
# the alternative to showing it is halting the machine that holds the only
# copy.
#
# ed is cmd/ed.c, the LOOSE one -- there is also a cmd/ed/ed.c carrying
# ansi.h and posix.h, and source_for() prefers the loose file.  That is the
# right one here for a reason and not by luck: the loose ed.c includes only
# <signal.h> and <setjmp.h> and has no prototype in it, so pcc2 can compile
# it, while the cmd/ed/ version is the POSIX rewrite.
BUILDTOOLS = ["ar", "cmp", "tail", "ed"]

# The compiler, from source.  THIS IS WHAT STAGE 1 IS.
#
# The golden's toolchain today is a MIXTURE: ccom, as and libc.a are the
# tape's 1995 binaries, and cpp, c2 and ld were compiled by V8's cc under
# tools/v10tc.exp.  That was the right way to reach a running machine and it
# is the wrong thing to keep -- a V10 whose compiler passes were built by the
# previous edition is not a V10 that built itself.  Stage 1 rebuilds every
# pass from V10 source with V10's own compiler, on V10.
#
# Each entry's link list is the tape's own, quoted in `note'.  Two of them
# differ from V8's list for the same programs, which is exactly why they were
# read rather than assumed:
#
#   ccom  V10's OFILES has genmore.o and does NOT have local2.o, memcpy.o or
#         t2print.o -- V8's has the latter three and no genmore.  Same program,
#         eight years apart.  reader.o and printx.o resolve to the vax/ copies,
#         not common/'s: the makefile writes `$(CC_CMD) reader.c' with no $M,
#         and both directories contain a file of each name.
#   c2    no ldflags.  V8's links with -z; V10's Makefile leaves LDFLAGS empty.
#
# yacc is FIRST and is not optional: cpp and ccom are both yacc grammars, and
# the tape ships yacc as source only -- there is no prebuilt binary for it
# anywhere in the tree.  It also reads /usr/lib/yaccpar at RUNTIME
# (cmd/yacc/files: `# define PARSER "/usr/lib/yaccpar"'), so the data file has
# to be installed too or every later grammar fails at a stage that looks like
# a grammar problem.
TOOLCHAIN = [
    dict(name="yacc", dir="cmd/yacc",
         objs=["y1.c", "y2.c", "y3.c", "y4.c"],
         cflags="-DWORD32",
         product="yacc", install="usr/bin/yacc",
         data=[("yaccpar", "usr/lib/yaccpar")],
         note="cmd/yacc/Makefile: yacc: y1.o y2.o y3.o y4.o; CFLAGS=-O -DWORD32; "
              "install mv yacc $(DESTDIR)/usr/bin, cp yaccpar $(DESTDIR)/usr/lib"),

    # cpp.  The mkfile builds four objects -- cpp.o cpy.o rodata.o yylex.o --
    # where rodata.c is what `sh :yyfix >rodata.c' lifts out of yacc's output
    # so the parser tables can be linked read-only.  WE SKIP :yyfix, exactly
    # as B1 did, and the deviation is safe for a reason worth stating: :yyfix
    # MOVES the tables, it does not create them, so a cpy.c that never had
    # them removed is still complete.  The cost is a few KB of data segment.
    #
    # V10's :yyfix is not V8's.  V8's takes the array names as arguments;
    # V10's takes none and writes to stdout (`sh :yyfix >rodata.c').  Anyone
    # reinstating it must read the tape's own copy, not port ours across.
    dict(name="cpp", dir="cmd/cpp",
         objs={"cpp.o": "cpp.c", "cpy.o": "cpy.c", "yylex.o": "yylex.c"},
         gen={"cpy.c": ("yacc -d", "cpy.y", "mv y.tab.c cpy.c")},
         # yacc -d writes y.tab.h beside cpy.c, in the OBJECT directory, and
         # yylex.c includes it.  Nothing can find it by scanning the share.
         sidegen={"y.tab.h": "cpy.c"},
         objdeps=["y.tab.h"],
         cflags="-DPRAGMA -DFLEXNAMES -DPD_MACH=D_vax -DPD_SYS=D_unix",
         product="cpp", install="lib/cpp",
         note="cmd/cpp/mkfile: OBJECTS=cpp.o cpy.o rodata.o yylex.o "
              "(rodata skipped, see above); install cp cpp /lib"),

    dict(name="ccom", dir="cmd/ccom/vax",
         objs={
             "cgram.o":   "cgram.c",
             "xdefs.o":   "../common/xdefs.c",
             "scan.o":    "../common/scan.c",
             "pftn.o":    "../common/pftn.c",
             "trees.o":   "../common/trees.c",
             "optim.o":   "../common/optim.c",
             "local.o":   "local.c",
             "reader.o":  "reader.c",
             "debug.o":   "debug.c",
             "common1.o": "../common/common1.c",
             "pjw.o":     "../common/pjw.c",
             "gencode.o": "gencode.c",
             "genaux.o":  "genaux.c",
             "genmore.o": "genmore.c",
             "printx.o":  "printx.c",
             "lookup.o":  "../common/lookup.c",
             "lcatch2.o": "lcatch2.c",
             "catch2.o":  "../common/catch2.c",
         },
         # yacc's #line directives are commented out because the C compiler
         # being fed them chokes on them in a generated file -- the tape's own
         # sed, kept verbatim.
         gen={"cgram.c": ("yacc", "../common/cgram.y",
                          "sed 's_^# line .*_/* & */_' y.tab.c >cgram.c; "
                          "rm -f y.tab.c")},
         incs=[".", "../common"], cflags="-DVAX -DYYDEBUG",
         # The tape puts -DYYMAXDEPTH=300 on cgram.o alone.  Kept per-object
         # rather than global: it is a parser stack size and means nothing to
         # the other seventeen.
         oflags={"cgram.o": "-DYYMAXDEPTH=300"},
         # cgram.o wants y.debug present and the tape ships y.debug.sv for it.
         # Named by full path: a bare `cp y.debug.sv y.debug' looks in the
         # object directory, where an out-of-tree build has no such file.
         pre=["cp $(SRC)/cmd/ccom/vax/y.debug.sv y.debug"],
         product="comp", install="lib/ccom",
         note="cmd/ccom/vax/makefile: OFILES (18); INCLIST=-I. -I../common; "
              "TARGET=-DVAX; install cp comp /lib/ccom"),

    # as.  aspseudo.c #includes `instrs', a 200 KB data file in the source
    # directory, which is why incs must keep "." -- it is found by -I, not by
    # being beside the object.
    #
    # The tape compiles aspseudo.o to assembly, runs :rofix on it, and
    # assembles that, to move the reserved-word tables into shared text.  Same
    # class of optimisation as cpp's :yyfix and skipped for the same reason:
    # it relocates data that is correct either way.
    dict(name="as", dir="cmd/as",
         objs=["asscan.c", "asparse.c", "asexpr.c", "asmain.c", "assyms.c",
               "asjxxx.c", "ascode.c", "aspseudo.c", "asio.c"],
         cflags="-DUNIX -DUNIXDEVEL -DFLEXNAMES",
         product="as", install="bin/as",
         note="cmd/as/Makefile: OBJS (9); CFLAGS=-O -DUNIX -DUNIXDEVEL "
              "-DFLEXNAMES; install mv as ${DESTDIR}/bin"),

    dict(name="c2", dir="cmd/c2", objs=["c20.c", "c21.c", "c22.c"],
         cflags="-DCOPYCODE",
         # `$(CC) $(CFLAGS) -cR c22.c' -- the peephole tables go read-only.
         oflags={"c22.o": "-R"},
         product="c2", install="lib/c2",
         note="cmd/c2/Makefile: FILES=c20.o c21.o c22.o, c22 with -cR, "
              "LDFLAGS empty (V8's links -z; V10's does not); "
              "install cp c2 $(DESTDIR)/lib"),
]

# The two passes that are ONE loose cmd/*.c, so component() builds them from
# where.txt like any other command.  cc is read from our overlay -- it uses
# BUFSIZE without including <sys/param.h>, mv.c's defect with a different
# constant -- which PATCHED below already arranges.
TOOLCHAIN_SIMPLE = ["ld", "cc"]

# Components read from OUR overlay rather than from the pristine tarball.
#
# tools/v10-overlay.py derives v10/src/ from named upstream files with stated
# hashes, and v10/src/PATCHES.md carries the diffs and the reasoning.  Listing
# them here makes the generated makefile say which is which: a rule reading
# $(SRC) is Bell Labs', a rule reading $(OURS) is ours.  Both were measured by
# tools/v10-bootpath.sh; every other boot-path command built clean.
OURS = os.path.join(V10, "src")
PATCHED = {
    # `#include <stat.h>' names a header the archive does not have -- and
    # `/* #include <sys/stat.h> */' is commented out on the line above it.
    "fsck",
    # uses ROOTINO and includes nothing that defines it.  Compiles against
    # V8's headers only because V8's sys/types.h includes sys/param.h.
    "mv",
    # uses BUFSIZE without including <sys/param.h> -- mv.c's defect with a
    # different constant.
    "cc",
    # its BITFS device check cannot be satisfied on a V8 host, where the same
    # bit is part of hp's drive number.  Left out of this set once already,
    # and the run then used the TARBALL's copy and died with the tarball's
    # message -- "can't have a 4k filesystem" -- which reads like the port
    # not working rather than the port not being used.
    "mkbitfs",
}


# ---------------------------------------------------------------- libc ---
#
# STAGE 2, and it is deliberately not another entry in a component table:
# libc is an ARCHIVE, not a program, and almost every step of the tape's
# recipe for it is a special case.  v8/mk/mkdep.py separates it for the same
# reason.
#
# WHAT IS DIFFERENT HERE IS THE EVIDENCE.  V8's emit_libc() has to
# RECONSTRUCT the object list by walking crt/ gen/ math/ stdio/ sys/ in the
# tape's compile order and letting a later directory overwrite an earlier one,
# because usr/src/libc/Makefile compiles `gen/*.[cs]' with a glob and four
# basenames appear twice.  V10's mkfile names every object and its source:
#
#	OBJ=$L(_assert.o) $L(_cleanup.o) $L(_exit.o) ...      261 of them
#	...
#	strcat.o:	gen/strcat.s
#	asin.o:		math/asin.c
#
# All 261 have an explicit source line, and that set is EXACTLY the 261
# objects in the tape's own libc.a.  So nothing below is inferred: the object
# list, the sources and the member ORDER are read off artefacts Bell Labs
# shipped, and any disagreement between them is a hard error rather than a
# silent preference.
#
# MEMBER ORDER COMES FROM THE ARCHIVE, NOT FROM `lorder | tsort'.  V8's
# recipe reorders with `ar cr libc.a `lorder *.o | tsort`` because its ld
# walks an archive once and a backward reference never resolves.  V10's ld is
# the same program -- cmd/ld.c carries the same comment, "you can get away
# with backward references when there is a table of contents!" -- but the
# golden has NEITHER lorder NOR tsort; neither is among its 57 prebuilt
# commands.  It does not need them.  The tape's libc.a is Bell Labs' own
# answer to the ordering question, so the order is read out of it.  ranlib
# then writes __.SYMDEF and the order stops being load-bearing anyway; keeping
# it makes our archive comparable to the tape's member by member, which is
# what stage 2 is measured by.
#
# TEN MEMBERS WERE NOT BUILT BY THE C COMPILER.  The mkfile overrides the
# default recipe with `lcc' for malloc, memmove, qsort, fgets, fputs, rdwr,
# scanf, sprintf, vfprintf and vfscanf -- lcc being the ANSI compiler in
# cmd/lcc, whose headers are the ones r70 installs at /usr/include/lcc.  We
# emit those ten with $(COMPILE) like the other 251 and let the run say what
# happens, because the alternative is assuming pcc2's answer instead of
# measuring it.  The set is derived from the mkfile rather than typed, and it
# is written into the generated makefile so the artefact carries the fact.
#
# There is no prebuilt lcc DRIVER we can use even if we wanted to: cmd/lcc/etc/
# lcc is compiled from bowell.c and its strings name `/usr/lib/gcc-cpp' and
# `/usr/lib/rcc'.  The tree has rcc (gen2/vax-v9/rcc) and has NO gcc-cpp
# anywhere -- only cmd/gcc/gcc.c, source.
LIBC_DIR = "libc"

# The members pcc2 CANNOT compile, so the makefile hands them to lcc instead.
#
# MEASURED, NOT TAKEN FROM THE MKFILE, and the difference is the whole point.
# The mkfile overrides only ten recipes with `lcc'; twenty-five members
# actually need it.  V10 was never built from scratch -- it accreted -- so the
# tape's own makefile is not a reliable statement of which compiler a file
# needs, and treating it as one leaves fifteen members failing on
# `syntax error' with the makefile insisting they are cc's.
#
# This list is what tools/v10-stage2.sh reported after a `make -k' over all
# 261 with pcc2 alone.  Every failure is an ANSI construct:
#
#	int fprintf(FILE *f, const char *fmt, ...)      prototypes, varargs
#	extern void *memcpy(void*, void*, size_t)       void *, size_t
#	static void swapfunc(char *, char *, size_t, int)
#	#include <stdarg.h>                             va_list
#
# The ten the mkfile names are marked; the other fifteen are ours to have
# found.  If a future run finds a twenty-sixth, add it here with the same
# evidence -- the alternative is a build that quietly drops a member.
LIBC_LCC = [
    # the ten the tape's mkfile already hands to lcc
    "fgets.o", "fputs.o", "malloc.o", "memmove.o", "qsort.o",
    "scanf.o", "sprintf.o", "vfprintf.o", "vfscanf.o", "rdwr.o",
    # rdwr.o was left on cc for one run, on the strength of a measurement
    # that said pcc2 compiled it.  It does not: the next run reported it as
    # the ONE remaining failure.  The tape's mkfile routes it to lcc and the
    # tape was right -- when the measurement and the mkfile disagree, re-run
    # the measurement before believing it.
    # fifteen more, measured
    "_dtoa.o", "_fconv.o", "fprintf.o", "fscanf.o", "getshares.o",
    "getshput.o", "jterm.o", "openshares.o", "printf.o", "putshares.o",
    "setlimits.o", "setupshares.o", "snprintf.o", "sscanf.o", "strtod.o",
    "vprintf.o",
]


def libc_from_tape():
    """The build plan for libc, read off the tape rather than typed.

    Returns (order, objmap, lcc):
      order   member order of the tape's own libc.a, __.SYMDEF removed
      objmap  object -> source path, relative to src/libc
      lcc     the objects whose recipe the mkfile overrides with lcc
    """
    d = os.path.join(SRC, LIBC_DIR)
    mkf = os.path.join(d, "mkfile")
    arc = os.path.join(d, "libc.a")
    for p in (mkf, arc):
        if not os.path.exists(p):
            sys.exit("mkdep: no %s -- run tools/v10-import.py" % p)

    text = open(mkf).read()
    m = re.search(r"^OBJ=(.*?)(?=\n[A-Z])", text, re.S | re.M)
    if not m:
        sys.exit("mkdep: %s has no OBJ= list" % mkf)
    objs = re.findall(r"\$L\(([^)]+)\)", m.group(1))

    # object -> source, plus whichever recipe line follows it.  mk's own
    # syntax: a target line at column 0, its recipe indented with a tab.
    objmap, lcc, cur = {}, set(), None
    for line in text.splitlines():
        r = re.match(r"^([A-Za-z_0-9]+\.o):[ \t]+([^\s:]+)", line)
        if r:
            cur, objmap[r.group(1)] = r.group(1), r.group(2)
            continue
        if line.startswith("\t"):
            if cur and "lcc" in line.split():
                lcc.add(cur)
            continue
        cur = None

    order, data, off = [], open(arc, "rb").read(), 8
    if data[:8] != b"!<arch>\n":
        sys.exit("mkdep: %s is not an ar archive" % arc)
    while off + 60 <= len(data):
        h = data[off:off + 60]
        if h[58:60] != b"`\n":
            sys.exit("mkdep: %s: bad member header at byte %d" % (arc, off))
        name = h[0:16].decode().rstrip()
        size = int(h[48:58].decode().strip())
        if name != "__.SYMDEF":
            order.append(name)
        off += 60 + size + (size & 1)

    # THE TWO ARTEFACTS MUST AGREE, and a mismatch stops the generator.  A
    # tarball re-import that changed either one would otherwise produce a
    # makefile that builds a library nobody shipped, and the difference would
    # not show up until something failed to link much later.
    gap = [o for o in objs if o not in objmap]
    if gap:
        sys.exit("mkdep: %s lists %s in OBJ with no source line"
                 % (mkf, " ".join(gap)))
    if set(order) != set(objs):
        only_a = sorted(set(order) - set(objs))
        only_m = sorted(set(objs) - set(order))
        sys.exit("mkdep: the tape's libc.a and its mkfile disagree -- "
                 "only in the archive: %s; only in the mkfile: %s"
                 % (" ".join(only_a) or "none", " ".join(only_m) or "none"))
    return order, objmap, sorted(lcc)


def emit_libc():
    order, objmap, _mkfile_lcc = libc_from_tape()
    lcc = LIBC_LCC
    lccset = set(lcc)
    unknown = lccset - set(order)
    if unknown:
        sys.exit("mkdep: LIBC_LCC names %s, which is not a libc member"
                 % " ".join(sorted(unknown)))
    d = os.path.join(SRC, LIBC_DIR)
    srcdir = "$(SRC)/" + LIBC_DIR

    def dep(path):
        path = os.path.normpath(path)
        if path.startswith(INC + os.sep):
            return "$(INCDIR)/" + mkgen.rel(path, INC)
        return srcdir + "/" + mkgen.rel(path, d)

    out = [PREAMBLE % dict(name="libc", cflags="", incs="")]
    out.append("""\
# Not in the shared preamble because libc is the only thing that needs it.
# ranlib writes __.SYMDEF, and cmd/ld.c reads it: with a current one ld makes
# as many passes as it takes, without one it makes exactly one and warns.
RANLIB = /usr/bin/ranlib

# THE SECOND COMPILER, AND IT IS NOT A CONCESSION.  V10 was never built from
# scratch, so its per-file compiler requirement is mixed: 25 of these 261
# members are ANSI and pcc2 cannot parse them.  lcc is Bell Labs' own 1995
# binary off the same tape -- the same provenance as ccom and as -- and its
# driver's paths are compiled in, so it must be installed as /usr/bin/lcc
# with /usr/lib/rcc and /usr/lib/gcc-cpp beside it.
#
# LCCARGS is the tape's own, from libc/mkfile, less the -c it adds per rule.
LCC     = lcc
LCCPATH = /usr/bin/lcc
LCCARGS = -N -I$(SRC)/libc/stdio -I$(INCDIR)/lcc -I$(INCDIR)/libc -I$(INCDIR) -DV10

""")
    out.append("# The %d members compiled by $(LCC), because pcc2 cannot parse them.\n"
               % len(lcc))
    out.append("# Measured by tools/v10-stage2.sh, NOT read from the mkfile -- which\n"
               "# names only ten and is wrong about fifteen.  See mkdep.py.\n")
    out.append("#   " + " ".join(sorted(lcc)) + "\n\n")
    out.append("OBJS = " + " ".join(order) + "\n")
    out.append("""
all: libc.a crt0.o mcrt0.o

# The objects alone, so a driver can run `make -k objs' and find out how many
# of the 261 this compiler can build BEFORE anything depends on all of them.
# Without it a single member that will not compile takes the whole run down
# to nothing -- no archive, no comparison, no measurement, four hours gone.
objs: $(OBJS)

# TWO RULES, AND THE STAMP FILE IS THE REASON.  `ld -x -r' REWRITES each
# object in place, so doing it inside the libc.a recipe leaves all 261
# prerequisites newer than the archive the moment the recipe finishes -- the
# install pass then rebuilds the whole thing a second time and an incremental
# build never converges.  `stripped' is written after the objects it rewrote,
# so it is newer than all of them and libc.a is newer than it.
#
# The loop is over *.o and not over $(OBJS), which matters after a `make -k'
# that could not build every member: the strip pass then covers what exists
# instead of stopping at the first name with no file.
stripped: $(OBJS)
	-for i in *.o ; do $(LD) -x -r $$i; mv a.out $$i; done
	echo stripped > stripped

# `cr' and not `uv': the member order is the tape's, and an update would
# append anything missing at the end instead.  rm first, because `cr' on an
# existing archive replaces members rather than starting over.
libc.a: stripped
	rm -f libc.a
	$(AR) cr libc.a $(OBJS)
	$(RANLIB) libc.a

# gen/:errfix moves the error-message table out of .data and into shared
# text: errlst.c is compiled to ASSEMBLY, edited, and only then assembled.
# The filename really does begin with a colon -- a V7 convention for a script
# that is not a command you would type.
#
# -S rather than -c, and the output lands HERE and not on the share: cc.c's
# setsuf() walks the path and returns the basename, so `cc -S /n/v10/src/...
# /errlst.c' writes errlst.s into the object directory.  That is what makes
# the whole out-of-tree build possible and it is worth knowing where it comes
# from.
errlst.o: %(src)s/gen/errlst.c $(TOOLS)
	$(CC) $(CFLAGS) $(INCS) -S %(src)s/gen/errlst.c
	ed - errlst.s < %(src)s/gen/:errfix
	$(AS) -o errlst.o errlst.s
	rm -f errlst.s
""" % dict(src=srcdir))

    # crt0.o and mcrt0.o are built here but are NOT members: they are the
    # startup files ld links in front of every program.
    for obj in order + ["crt0.o", "mcrt0.o"]:
        if obj == "errlst.o":
            continue
        src = objmap.get(obj, "csu/" + obj[:-2] + ".s")
        path = os.path.join(d, src)
        deps = [srcdir + "/" + src] + [
            x for x in sorted(dep(y) for y in mkgen.scan_includes(path, [INC]))
            if x != srcdir + "/" + src]
        if obj in lccset:
            # $(LCCPATH), not $(TOOLS): this object does not go through ccom,
            # c2 or cpp at all, so naming them as prerequisites would rebuild
            # it whenever a pass it never runs changes.
            out.append("\n%s: %s $(LCCPATH)\n\t$(LCC) $(LCCARGS) -c %s/%s\n"
                       % (obj, " ".join(deps), srcdir, src))
        else:
            out.append("\n%s: %s $(TOOLS)\n\t$(COMPILE) %s/%s\n"
                       % (obj, " ".join(deps), srcdir, src))

    # Into $(TOOLDIR)/lib, never over the libc being compiled against.  The
    # tape's own install target opens `cp $(DESTDIR)/lib/libc.a liboc.a; cp
    # libc.a $(DESTDIR)/lib/libc.a' -- it overwrites the running system's.
    out.append("\ninstall: libc.a crt0.o mcrt0.o\n")
    out.extend(mkgen.mkdirs_for("$(TOOLDIR)", "lib/libc.a"))
    out.append("\tcp libc.a $(TOOLDIR)/lib/libc.a\n")
    # RANLIB AFTER THE COPY.  cp gives the archive a new mtime while __.SYMDEF
    # keeps the old one, and ld reads that as "table of contents out of date"
    # -- one sequential pass, a warning naming ranlib, and undefined symbols
    # in something that linked fine a minute earlier.
    out.append("\t$(RANLIB) $(TOOLDIR)/lib/libc.a\n")
    out.append("\tcp crt0.o $(TOOLDIR)/lib/crt0.o\n")
    out.append("\tcp mcrt0.o $(TOOLDIR)/lib/mcrt0.o\n")
    out.append("\nclean:\n\t-rm -f $(OBJS) crt0.o mcrt0.o libc.a stripped\n")
    return "".join(out)


def source_for(name, root):
    """Where this command's source is: cmd/<name>.c, or cmd/<name>/<name>.c."""
    loose = os.path.join(root, "cmd", name + ".c")
    if os.path.exists(loose):
        return "cmd", name + ".c"
    indir = os.path.join(root, "cmd", name, name + ".c")
    if os.path.exists(indir):
        return "cmd/" + name, name + ".c"
    return None, None


def component(name):
    """One entry for mkgen.emit(), or None with a reason."""
    # A host tool is `v10<something>'; its SOURCE is the unprefixed name.
    host = name.startswith("v10")
    srcname = name[3:] if host else name
    patched = srcname in PATCHED
    root = OURS if patched else SRC
    d, src = source_for(srcname, root)
    if d is None:
        if patched:
            return None, ("listed as patched but not in v10/src -- "
                          "run tools/v10-overlay.py")
        return None, "no source in cmd/"
    if host:
        # Host tools land beside the V10 toolchain, never on V8's PATH, and
        # under TOOLDIR rather than the image's DESTDIR.
        c = dict(name=name, dir=d, objs=[src], product=name,
                 install="bin/" + name, dest="TOOLDIR")
        if patched:
            c["root"], c["srcmacro"] = OURS, "OURS"
        return c, None
    where = WHERE.get(srcname)
    if not where:
        return None, "no install path (tools/v10-where.py says unresolved)"
    c = dict(name=name, dir=d, objs=[src], product=name,
             install=where[0].lstrip("/") + "/" + name, dest="DESTDIR")
    if patched:
        # Read from the overlay, and SAY SO in the generated rule.  The point
        # is that provenance survives into the artefact: someone reading
        # gen/fsck.mk in a year can see at a glance that this one source is
        # ours and every other is Bell Labs'.
        c["root"] = OURS
        c["srcmacro"] = "OURS"
    return c, None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed makefiles are stale")
    args = ap.parse_args()

    if not os.path.isdir(SRC):
        sys.exit("mkdep: no %s -- run tools/v10-import.py" % SRC)

    os.makedirs(GEN, exist_ok=True)
    stale, written, entries, skipped = [], set(), [], []

    def put(name, text):
        # FOURTEEN BYTES.  Every file generated here is copied onto a guest
        # filesystem, and a Research Unix directory entry is 14 characters --
        # a longer name is TRUNCATED, silently, with a successful exit status.
        #
        # `toolchain.order' is 15 and arrived on the source disk as
        # `toolchain.orde', which read as a copy that had not happened.  This
        # is the project's fourth time: `streamio.c.orig' (15) failed with a
        # bare "cp: cannot create", and `install-prebuilt.sh' (19) with
        # "sh: cannot open".  Each was fixed and none of them stopped the
        # next one, so the rule goes in the generator rather than in a
        # comment.
        if len(name) > 14:
            raise SystemExit(
                "mkdep: '%s' is %d characters -- a Research Unix directory "
                "entry is 14, so this name is silently truncated to '%s' the "
                "moment it reaches a guest.  Shorten it."
                % (name, len(name), name[:14]))
        if name in written:
            raise SystemExit("mkdep: two components both generate %s" % name)
        written.add(name)
        path = os.path.join(GEN, name)
        old = open(path).read() if os.path.exists(path) else None
        if args.check:
            if old != text:
                stale.append(name)
        elif old != text:
            open(path, "w").write(text)

    for name in BOOTPATH + FSTOOLS + SHUTDOWN + BUILDTOOLS + TOOLCHAIN_SIMPLE:
        c, why = component(name)
        if c is None:
            skipped.append((name, why))
            continue
        put(name + ".mk", mkgen.emit(V10ED, c))
        entries.append((name, c["dir"], c["install"]))

    # The multi-file toolchain components carry their own dicts: each is a
    # DIRECTORY of sources with no <name>.c, so component()'s heuristic --
    # which finds every ordinary command -- finds none of the compiler.
    tcnames = []
    for c in TOOLCHAIN:
        put(c["name"] + ".mk", mkgen.emit(V10ED, c))
        entries.append((c["name"], c["dir"], c["install"]))
        tcnames.append(c["name"])

    # STAGE 2.  An archive, not a program, so it has its own emitter rather
    # than a component dict -- see emit_libc().
    put("libc.mk", emit_libc())
    entries.append(("libc", LIBC_DIR, "lib/libc.a"))
    # The member list as DATA, in the tape's own order, so the guest can walk
    # it from `sh'.  A driver has to answer "which of the 261 are missing?"
    # and V10 has no wc and no grep -- what it does have is a for loop, and
    # this is the file it reads.
    put("libc.ord", "".join(o + "\n" for o in libc_from_tape()[0]))
    # object -> source, as DATA, so the guest can compile one member by name
    # without a makefile.  `sed -n "s/^$o //p" libc.src' is the whole lookup.
    #
    # This is what lets stage 2 ask the question that matters about a member
    # whose bytes differ from the tape's: WHICH COMPILER did Bell Labs use?
    # Recompile it with lcc, strip it the way the tape does, and compare
    # again -- a match names the compiler, and a set of such matches turns
    # "V10 was never built from scratch" from a warning into a map.
    _order, _objmap, _ = libc_from_tape()
    put("libc.src", "".join("%s %s\n" % (o, _objmap[o]) for o in _order))

    put("bootpath.order",
        "".join("%s\t%s\t%s\n" % e
                for e in entries if e[0] in BOOTPATH))
    put("fstools.order",
        "".join("%s\t%s\t%s\n" % e
                for e in entries if e[0] in FSTOOLS))
    put("shutdown.order",
        "".join("%s\t%s\t%s\n" % e
                for e in entries if e[0] in SHUTDOWN))
    put("buildtools.ord",
        "".join("%s\t%s\t%s\n" % e
                for e in entries if e[0] in BUILDTOOLS))
    # ORDER IS THE POINT HERE, unlike the lists above.  yacc must exist before
    # cpp or ccom can be built from a grammar, and every later pass is built
    # by the passes before it, so this file is a sequence and not a set.
    tcorder = tcnames + [n for n in TOOLCHAIN_SIMPLE if n in dict(
        (e[0], e) for e in entries)]
    put("tc.order",
        "".join("%s\t%s\t%s\n" % dict((e[0], e) for e in entries)[n]
                for n in tcorder))

    # What was NOT covered, and why -- generated rather than commented, so it
    # cannot drift from the code that produced it.  A build that silently
    # covers less than it appears to is worse than one that covers less and
    # says so; V8's stage 6 shipped `bcd' built, reported, and absent because
    # of exactly this gap.
    put("bootskip.txt",
        "# Boot-path commands v10/mk/mkdep.py did not emit a makefile for.\n"
        "# Regenerated by v10/mk/mkdep.py.\n#\n"
        + "".join("%-10s %s\n" % s for s in skipped))

    # NOTHING MAY WRITE OUTSIDE A MACRO, and nothing may write to `/'.
    # These makefiles run on a live Eighth Edition host with its own mkfs,
    # mknod, dd and cpio; a rule that reached /bin or /lib would replace a
    # V8 tool with a V10 one and the damage would surface much later.
    import re as _re
    for name in sorted(written):
        if not name.endswith(".mk"):
            continue
        text = open(os.path.join(GEN, name)).read()
        for line in text.splitlines():
            m = _re.match(r"\t(?:-mkdir|cp|mv)\s+(.*)", line)
            if not m:
                continue
            dest = m.group(1).split()[-1]
            # A BARE FILENAME IS THE OBJECT DIRECTORY, and that is where a
            # build is supposed to write.  ccom's `cp $(SRC)/.../y.debug.sv
            # y.debug' is the case: the tape needs y.debug beside the object,
            # and naming it through a macro would put it somewhere else.
            #
            # What must go through a macro is anything that NAMES a location
            # -- an absolute path, or a relative one that walks out of here.
            # That is the whole of the risk: this build runs on a live Eighth
            # Edition host, so `cp c2 /lib' would replace V8's peephole
            # optimiser with V10's and the damage would surface later,
            # somewhere else, in something that had been working.
            if "/" in dest and not dest.startswith("$("):
                raise SystemExit(
                    "mkdep: %s writes to a literal path (%s) -- a destination "
                    "naming a directory must go through $(DESTDIR) or "
                    "$(TOOLDIR)" % (name, dest))
    for macro in ("DESTDIR", "TOOLDIR"):
        if ("\n%-8s= /" % macro).replace("%-8s", macro.ljust(8)) not in PREAMBLE:
            raise SystemExit("mkdep: PREAMBLE has no absolute %s default; an "
                             "empty one would write into the host's /" % macro)

    if args.check:
        if stale:
            print("stale, re-run v10/mk/mkdep.py: " + " ".join(stale))
            return 1
        print("makefiles are up to date with the source tree")
        return 0

    print("generated %d of %d components in %s"
          % (len(entries),
             len(BOOTPATH) + len(FSTOOLS) + len(SHUTDOWN)
             + len(BUILDTOOLS) + len(TOOLCHAIN_SIMPLE) + len(TOOLCHAIN) + 1,
             mkgen.rel(GEN, os.getcwd())))
    order, _, lcc = libc_from_tape()
    print("  libc       %d members, order read from the tape's libc.a; "
          "%d built with lcc there" % (len(order), len(lcc)))
    if skipped:
        for name, why in skipped:
            print("  skipped %-10s %s" % (name, why))
    if not WHERE:
        print("  NO v10/mk/where.txt -- run tools/v10-where.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
