#!/usr/bin/env python3
"""
Generate the makefiles the Tenth Edition never had either.

    v10/mk/mkdep.py            # regenerate v10/mk/gen/*.mk
    v10/mk/mkdep.py --check    # fail if the committed output is stale

V8 needed this because `usr/src/cmd` is 168 loose `.c` files under a directory
with no makefile in it. B2.0 measured V10's tree and found the same shape --
207 loose `.c` files, no makefile at `cmd/`, and no world build anywhere. The
one candidate, `src/makefile`, builds a Datakit daemon called `fshare`.

So this is `v8/mk/mkdep.py`'s sibling, not its copy: the machinery lives in
`mk/mkgen.py` and what is here is what differs between the two editions --
the toolchain, the header set, the install oracle and the exceptions.

WHAT IS DIFFERENT, AND IT IS SHORTER THAN THE SIMILARITY

  no bootstrap    V8's generator opens with a 136-line STAGE1 table building
                  yacc, make, lex, cpp, ccom, c2, as, ld, ar... because a
                  self-hosting build has to make its own compiler first. V10's
                  compiler, assembler and libc are IN THE TARBALL as linked
                  VAX binaries and run on the V8 kernel (B1, 9/9), so there is
                  no stage 1 here at all. `tools/v10-toolchain.sh` assembles
                  the seven passes and `cc -B/usr/v10/lib/ -t02palc` drives
                  them.

  a paper oracle  V8's install paths were MEASURED off the shipped image.
                  V10 has no image -- making one is B3 -- so the paths come
                  from V10's own manual where it states them and from V8's
                  measurements where it does not. tools/v10-where.py, and the
                  two sources agree everywhere both speak.

  r70 headers     `-I` points at V10's own include tree, not V8's. B2.0 built
                  15 of 17 boot-path commands that way against 10 the other
                  way, so this is measured rather than assumed.
"""

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
V10 = os.path.dirname(HERE)                 # <repo>/v10
ROOT = os.path.dirname(V10)
GEN = os.path.join(HERE, "gen")

# The tree itself is NOT in git -- 25,682 files rebuilt from the TUHS tarballs
# by tools/v10-import.py, so the tarballs stay pristine and our changes stay a
# patch series. v10/MANIFEST is the committed record that our copy is
# complete and unaltered.
SRC = os.path.join(ROOT, "work/v10/src")
INC = os.path.join(ROOT, "work/v10/include")

sys.path.insert(0, os.path.join(ROOT, "mk"))
import mkgen                                                  # noqa: E402


PREAMBLE = """\
# Generated by v10/mk/mkdep.py -- do not edit; edit the generator.
#
# Run from the component's object directory:
#     make -f $SRC/../mk/%(name)s.mk DESTDIR=... install
#
# Every object below depends on the compiler passes that produced it, so
# replacing $(CCOM) rebuilds all of them; every binary depends on $(LD) and
# $(LIBC).

# Source is READ ONLY and lives on the netfs share -- the whole 243 MB tree is
# served, never copied, so no subset ever has to be chosen.  Objects are
# written into the current directory, which the driver makes a per-component
# directory on a writable filesystem.
SRC     = /n/v10/src

# TWO destinations, and neither is `/'.
#
# DESTDIR is the V10 system being assembled -- the tree that becomes the
# image.  TOOLDIR is where tools that RUN ON THE HOST are installed, beside
# the V10 toolchain and off V8's PATH.
#
# A DEFAULT IS LOAD-BEARING HERE.  An unset $(TOOLDIR) expands to nothing, so
# `cp v10mkbitfs $(TOOLDIR)/bin/v10mkbitfs' would write into the HOST's /bin.
# That is not hypothetical -- this file shipped without a TOOLDIR line, and
# the only thing between it and V8's /bin was that nothing had run the
# install target yet.
DESTDIR = /b/v10root
TOOLDIR = /usr/v10

# Our corrections, served beside the pristine tree rather than patched into
# it -- v10/MANIFEST is the record that our copy of the tarball is unaltered,
# and that is worth more than the convenience.  A rule below reading $(SRC)
# is Bell Labs'; one reading $(OURS) is ours.  See v10/src/PATCHES.md.
OURS    = /n/v10ours

# THE TOOLCHAIN IS V10's, AND V8 SUPPLIES ONLY THE DRIVER.
#
# -B names the directory holding the passes; -t says which passes to take from
# there.  `-t02palc' is S5's extended form -- 0 ccom, 2 c2, p cpp, a as, l ld,
# c crt0.o+libc.a -- so one prefix seals every program cc executes.  That seal
# was built so V8's own build could not reach into the running system; it
# turns out to be the lever that points a cc at another EDITION.
#
# $(CC) is what a rule runs.  $(CCPATH) is the file whose timestamp means "the
# compiler changed", which is what a prerequisite list needs -- writing
# `CC = cc' and then using $(CC) as a prerequisite gives
#	Make:  Don't know how to make cc.  Stop.
# on every component at once.
V10LIB   = /usr/v10/lib
CC       = cc -B$(V10LIB)/ -t02palc
CCPATH   = /bin/cc
YACC     = yacc
YACCPATH = /usr/bin/yacc
LEX      = lex
LEXPATH  = /usr/bin/lex
CPP  = $(V10LIB)/cpp
CCOM = $(V10LIB)/ccom
C2   = $(V10LIB)/c2
AS   = $(V10LIB)/as
LD   = $(V10LIB)/ld
AR   = /bin/ar
LIBC = $(V10LIB)/libc.a

# V10's own headers, copied to local disk rather than read off the share:
# netfs costs a round trip per path component, and a header is opened once per
# object that includes it.  tools/v10-bootpath.sh stages them with one
# `cpio -pd'.
INCDIR = /usr/v10/include

CFLAGS = -O %(cflags)s
INCS   = %(incs)s -I$(INCDIR)
COMPILE = $(CC) $(CFLAGS) $(INCS) -c
TOOLS  = $(CCPATH) $(CCOM) $(CPP) $(C2) $(AS)

"""

V10ED = mkgen.Edition(name="v10", root=SRC, incdir=INC,
                      here=HERE, gen=GEN, preamble=PREAMBLE)

WHERE = mkgen.load_where(V10ED)


# The seventeen B3 cannot start without.  Held explicitly rather than derived,
# because the ORDER and the membership are the point: this is the list that
# decides whether a disk boots, and a heuristic that quietly dropped one would
# be found at `/etc/init: not found' with the disk already built.
#
# It is also the set with NO prebuilt binary -- not one of the 46 command
# units with a 1995 binary is here, because these get installed rather than
# left where they were compiled.  There is no oracle for this list.
BOOTPATH = ["init", "getty", "login", "mount", "umount", "mkfs", "fsck",
            "icheck", "sync", "date", "stty", "cat", "cp", "mv", "rm",
            "mkdir", "echo"]

# The subset that MAKES a Tenth Edition filesystem, ported to run on the
# Eighth Edition host.  Built from V10 source and nothing else: V8 has files
# of the same names -- mkbitfs.c, mkfs.c -- and they are eight years apart,
# so using V8's would be assuming the on-disk format never changed rather
# than reading V10's own answer to it.
#
# `mkbitfs' is the one that matters.  seki's root is `ra 0100', and
# BITFS(dev) = ((dev) & 64), so its root filesystem is the BITMAPPED variant:
# 4096-byte blocks, and free space held in S_bfree[BITMAP] rather than in the
# S_free[] list.  mkfs writes only the free-list form -- it is a Berkeley 4.2
# file that uses BSIZE(0) throughout -- so mkfs alone cannot make a
# filesystem seki can mount.  mkbitfs can: it opens with
#
#	#define ISBIT 0100    /* this is a bitmapped filesystem -- fake out macros */
#	#define ICOUNT INOPB(ISBIT)
#	#define BCOUNT BSIZE(ISBIT)
#
# and sets s_valid = 1.  It checks BITFS(st_rdev) on its target, so the raw
# device node it is pointed at must carry bit 6 in its minor number.
# NAMED v10<tool>, AND THAT IS A SAFETY PROPERTY, NOT A CONVENTION.
#
# These run on the EIGHTH Edition host, beside V8's own mkfs, mknod, dd and
# cpio.  A V10 tool that answered to `mkfs' on that machine would be one
# PATH accident away from being the one a build reached for, and the failure
# would be silent: V10's mkfs writes a superblock V8's kernel reads
# differently, so the damage would appear later, somewhere else, as a
# corrupt filesystem.
#
# The tape shows how bad this gets left to convention.  V10's own
# cmd/ccom/vax/makefile carries
#
#	install:
#		cp /lib/ccom comp.sv
#		cp comp /lib/ccom
#
# -- it overwrites the compiler you are compiling with, in `/', on the host.
# Nothing generated here can do that (every destination goes through
# $(DESTDIR) or $(TOOLDIR), asserted below), but the names make the
# separation visible rather than merely true.
#
# Files that go INTO the V10 image keep their real names: `init' has to be
# /etc/init there.  The prefix is only for tools executed on the host.
FSTOOL_SRC = ["mkbitfs", "mknod", "dd", "cpio"]
FSTOOLS = ["v10" + n for n in FSTOOL_SRC]

# Components read from OUR overlay rather than from the pristine tarball.
#
# tools/v10-overlay.py derives v10/src/ from named upstream files with stated
# hashes, and v10/src/PATCHES.md carries the diffs and the reasoning.  Listing
# them here makes the generated makefile say which is which: a rule reading
# $(SRC) is Bell Labs', a rule reading $(OURS) is ours.  Both were measured by
# tools/v10-bootpath.sh; every other boot-path command built clean.
OURS = os.path.join(V10, "src")
PATCHED = {
    # `#include <stat.h>' names a header the archive does not have -- and
    # `/* #include <sys/stat.h> */' is commented out on the line above it.
    "fsck",
    # uses ROOTINO and includes nothing that defines it.  Compiles against
    # V8's headers only because V8's sys/types.h includes sys/param.h.
    "mv",
    # its BITFS device check cannot be satisfied on a V8 host, where the same
    # bit is part of hp's drive number.  Left out of this set once already,
    # and the run then used the TARBALL's copy and died with the tarball's
    # message -- "can't have a 4k filesystem" -- which reads like the port
    # not working rather than the port not being used.
    "mkbitfs",
}


def source_for(name, root):
    """Where this command's source is: cmd/<name>.c, or cmd/<name>/<name>.c."""
    loose = os.path.join(root, "cmd", name + ".c")
    if os.path.exists(loose):
        return "cmd", name + ".c"
    indir = os.path.join(root, "cmd", name, name + ".c")
    if os.path.exists(indir):
        return "cmd/" + name, name + ".c"
    return None, None


def component(name):
    """One entry for mkgen.emit(), or None with a reason."""
    # A host tool is `v10<something>'; its SOURCE is the unprefixed name.
    host = name.startswith("v10")
    srcname = name[3:] if host else name
    patched = srcname in PATCHED
    root = OURS if patched else SRC
    d, src = source_for(srcname, root)
    if d is None:
        if patched:
            return None, ("listed as patched but not in v10/src -- "
                          "run tools/v10-overlay.py")
        return None, "no source in cmd/"
    if host:
        # Host tools land beside the V10 toolchain, never on V8's PATH, and
        # under TOOLDIR rather than the image's DESTDIR.
        c = dict(name=name, dir=d, objs=[src], product=name,
                 install="bin/" + name, dest="TOOLDIR")
        if patched:
            c["root"], c["srcmacro"] = OURS, "OURS"
        return c, None
    where = WHERE.get(srcname)
    if not where:
        return None, "no install path (tools/v10-where.py says unresolved)"
    c = dict(name=name, dir=d, objs=[src], product=name,
             install=where[0].lstrip("/") + "/" + name, dest="DESTDIR")
    if patched:
        # Read from the overlay, and SAY SO in the generated rule.  The point
        # is that provenance survives into the artefact: someone reading
        # gen/fsck.mk in a year can see at a glance that this one source is
        # ours and every other is Bell Labs'.
        c["root"] = OURS
        c["srcmacro"] = "OURS"
    return c, None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed makefiles are stale")
    args = ap.parse_args()

    if not os.path.isdir(SRC):
        sys.exit("mkdep: no %s -- run tools/v10-import.py" % SRC)

    os.makedirs(GEN, exist_ok=True)
    stale, written, entries, skipped = [], set(), [], []

    def put(name, text):
        if name in written:
            raise SystemExit("mkdep: two components both generate %s" % name)
        written.add(name)
        path = os.path.join(GEN, name)
        old = open(path).read() if os.path.exists(path) else None
        if args.check:
            if old != text:
                stale.append(name)
        elif old != text:
            open(path, "w").write(text)

    for name in BOOTPATH + FSTOOLS:
        c, why = component(name)
        if c is None:
            skipped.append((name, why))
            continue
        put(name + ".mk", mkgen.emit(V10ED, c))
        entries.append((name, c["dir"], c["install"]))

    put("bootpath.order",
        "".join("%s\t%s\t%s\n" % e
                for e in entries if e[0] in BOOTPATH))
    put("fstools.order",
        "".join("%s\t%s\t%s\n" % e
                for e in entries if e[0] in FSTOOLS))

    # What was NOT covered, and why -- generated rather than commented, so it
    # cannot drift from the code that produced it.  A build that silently
    # covers less than it appears to is worse than one that covers less and
    # says so; V8's stage 6 shipped `bcd' built, reported, and absent because
    # of exactly this gap.
    put("bootpath-skipped.txt",
        "# Boot-path commands v10/mk/mkdep.py did not emit a makefile for.\n"
        "# Regenerated by v10/mk/mkdep.py.\n#\n"
        + "".join("%-10s %s\n" % s for s in skipped))

    # NOTHING MAY WRITE OUTSIDE A MACRO, and nothing may write to `/'.
    # These makefiles run on a live Eighth Edition host with its own mkfs,
    # mknod, dd and cpio; a rule that reached /bin or /lib would replace a
    # V8 tool with a V10 one and the damage would surface much later.
    import re as _re
    for name in sorted(written):
        if not name.endswith(".mk"):
            continue
        text = open(os.path.join(GEN, name)).read()
        for line in text.splitlines():
            m = _re.match(r"\t(?:-mkdir|cp|mv)\s+(.*)", line)
            if not m:
                continue
            dest = m.group(1).split()[-1]
            if not dest.startswith("$("):
                raise SystemExit(
                    "mkdep: %s writes to a literal path (%s) -- every "
                    "destination must go through $(DESTDIR) or $(TOOLDIR)"
                    % (name, dest))
    for macro in ("DESTDIR", "TOOLDIR"):
        if ("\n%-8s= /" % macro).replace("%-8s", macro.ljust(8)) not in PREAMBLE:
            raise SystemExit("mkdep: PREAMBLE has no absolute %s default; an "
                             "empty one would write into the host's /" % macro)

    if args.check:
        if stale:
            print("stale, re-run v10/mk/mkdep.py: " + " ".join(stale))
            return 1
        print("makefiles are up to date with the source tree")
        return 0

    print("generated %d of %d commands in %s"
          % (len(entries), len(BOOTPATH) + len(FSTOOLS),
             mkgen.rel(GEN, os.getcwd())))
    if skipped:
        for name, why in skipped:
            print("  skipped %-10s %s" % (name, why))
    if not WHERE:
        print("  NO v10/mk/where.txt -- run tools/v10-where.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
